### ISSUE TITLE
pre-existing zray.conf file causes nginx to fail

### ISSUE THREAD

**Issue by brandon-hoffman** [irazasyed/zray-installer#1]
I had followed the tutorial originally posted in laravel-news and then saw your comment with install script so I uninstalled but left the /etc/nginx/conf.d/zray.conf intact from original installation.  I followed the instructions on your site to install, btw great job! 
Your script appends the configuration to the /etc/nginx/conf.d/zray.conf if it was previously existing which caused nginx to fail to start properly.  I edited the zray.conf and removed the duplicate entry and restarted nginx an fpm and all worked properly.  

Even with this little issue it is a great script and I will be implementing it on our other dev machines today!  Great work and thanks for the contribution!

**Comment by irazasyed** [comment]
Hi @brandon-hoffman,

My pleasure :)

I seemed to have missed this issue ticket somehow.

Thanks for checking out the script and for commenting. 

As far as the issue is concerned, This script is mostly targeted to people who have never installed zray before. So assuming that, It does the job. I could add a way to probably remove it before setting up a new one. Thanks again for the input though.
